### ISSUE TITLE
Additional api calls

### ISSUE THREAD

**Issue by heban** [antonybudianto/cra-universal#103]
Hello @antonybudianto !

I would like to extend `app` object (which is instance of express) from `server/index.js`, with some extra routes, but I see it's impossible right now. For example I wanted to serve a JSON file and unfortunately it didn't work. I read similar issues:
https://github.com/antonybudianto/cra-universal/issues/33
https://github.com/antonybudianto/cra-universal/issues/20

but they are a little bit obsolete and urls from comments don't work anymore. Do You have solution for this case?

**Comment by hacknlove** [comment]
_Although I recommend using nginx for resolving the api calls instead of having it coupled with SSR server._

I agree with you when it comes to real world projects.

But there could be other use cases, like small examples in https://codesandbox.io/

Please, do not drop this feature.

Thank you very much for all your work.

**Comment by antonybudianto** [comment]
Hi @hacknlove , for sure! Custom server will always be supported
