### ISSUE TITLE
SSR for SVG loading or how to?

### ISSUE THREAD

**Issue by Falieson** [antonybudianto/cra-universal#12]
Sorry I'm noob at doing universal, thanks for making this script! I followed the instructions in a fresh CRA directory and visit localhost:3001 the app loads but the React logo doesn't. 

```
<header class="App-header"><img src="[object Object]" class="App-logo" alt="logo"><h1 class="App-title">Welcome to React</h1></header>
```

Thanks for your response

**Comment by antonybudianto** [comment]
Hi @Falieson ,

```
<img src="[object Object]"
```

Since you're loading the svg using "import"/"require" syntax, the CRA client will use its loader and generate hash for it. So when SSR happened, the element from client and server are not a match and thus not displayed.
The solution for now is that you can use normal relative path `<img src="./logo.svg"` rather than using import/require syntax

**Comment by antonybudianto** [comment]
@Grsmto , It depends on the loader too. For example, importing CSS is still fine, because I can use null-loader to exclude them on the server, but not working for SVG.
However you're correct about `server-side rendering is not actually using the same Webpack config as the frontend`
