### ISSUE TITLE
Rendering externally requested data server-side

### ISSUE THREAD

**Issue by krazyjakee** [antonybudianto/cra-universal#37]
I hope this is the right place to ask. On the client side, I could just use AJAX to retrieve external data and populate the view. How do I achieve this on the server side and avoid an AJAX request on the client?

**Comment by antonybudianto** [comment]
My current solution is to use Redux/Context API that works on server-side, also using axios or isomorphic-fetch. But since it's kinda opinionated solution, I don't put it on cra server template.

**Comment by krazyjakee** [comment]
I have been searching for a while. Is there a name or term for this? It might help with googling.

Also, is there any part about your solution that you would consider unopinionated?

**Comment by antonybudianto** [comment]
I'll probably create separate **@cra-express** package so it'll be an opinionated package.

Probably react-router one is not opinionated since react-router itself is already single major router used by all, unlike Redux which has many alternative like mobX, rematch, and finally React Context API (which may supersedes all). For the http client, the user should be allowed to use anything as long as they can return Promise, so it should be agnostic.

**Comment by antonybudianto** [comment]
I've POC on https://github.com/antonybudianto/cra-universal/tree/next-dev

**Comment by antonybudianto** [comment]
In short, https://github.com/antonybudianto/cra-universal/wiki/Server-side-fetch

You need to have:
- Redux store implemented, since fetch result will be stored there and the client just need to connect the store.
- React router with config file
